# Generated by Django 2.2.4 on 2019-12-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=50)),
                ('pic', models.ImageField(default='default.jpg', upload_to='pics')),
            ],
        ),
    ]
